export {Monitor} from "./core/Monitor";
import { WebEyeConfig } from "./types/index";
export type { WebEyeConfig };
export {ConsolePlugin} from "./plugins/ConsolePlugin";
export {RequestPlugin} from "./plugins/RequestPlugin";
export {ResourcePlugin} from "./plugins/ResourcePlugin";
export {ErrorPlugin} from "./plugins/ErrorPlugin";
export {CustomPlugin} from "./plugins/CustomPlugin";
export {WhiteScreenPlugin} from "./plugins/WhiteScreenPlugin";
export {PerformancePlugin} from "./plugins/PerformancePlugin";
export {RecordPlugin} from "./plugins/RecordPlugin";
